import "./globals.css";
import React from "react";

import type { Metadata } from "next";
import { ReactQueryProvider } from "@/components/ReactQueryProvider";
import Topbar from "@/components/layout/Topbar"
import Sidebar from "@/components/layout/Sidebar"
import {DM_Sans, Poppins} from "next/font/google";

const dmSans = DM_Sans({
    variable: "--font-dm-sans",
    subsets: ["latin", "latin-ext"],
    weight: ["1000"],
});

const poppins = Poppins({
    variable: "--font-poppins",
    subsets: ["latin", "latin-ext"],
    weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${dmSans.variable} ${poppins.variable} antialiased min-h-screen`}
      >
      <Topbar/>
      <Sidebar/>
      <ReactQueryProvider>
          {children}
      </ReactQueryProvider>
      </body>
    </html>
  );
}
