"""init schema

Revision ID: e77e4d0504a4
Revises: 
Create Date: 2025-11-20 17:18:30.783616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e77e4d0504a4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promotions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('promotion_type', sa.Enum('HELIX', 'UNION', 'GENERAL', name='promotion_enum'), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotions_is_deleted'), 'promotions', ['is_deleted'], unique=False)
    op.create_table('registration_invites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('role', sa.Enum('CLIENT', 'WORKER', 'BROKER', 'ADMIN', name='permissionrole'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('users',
    sa.Column('role', sa.Enum('CLIENT', 'WORKER', 'BROKER', 'ADMIN', name='permissionrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_table('admins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('is_super_admin', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dynamic_login_token', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('display_name')
    )
    op.create_table('brokers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('region', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_from_ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash'),
    sa.UniqueConstraint('user_id', 'token_hash', name='uix_user_token')
    )
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('workers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('department', sa.Enum('HELIX', 'UNION', name='department_enum'), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dynamic_login_token', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=True),
    sa.Column('taken_at_worker', sa.DateTime(), nullable=True),
    sa.Column('broker_id', sa.UUID(), nullable=True),
    sa.Column('taken_at_broker', sa.DateTime(), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.String(length=50), nullable=True),
    sa.Column('snils', sa.String(length=20), nullable=True),
    sa.Column('inn', sa.String(length=20), nullable=True),
    sa.Column('reg_address', sa.Text(), nullable=True),
    sa.Column('fact_address', sa.Text(), nullable=True),
    sa.Column('reg_date', sa.String(length=20), nullable=True),
    sa.Column('family_status', sa.String(length=50), nullable=True),
    sa.Column('workplace', sa.String(length=255), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('employment_date', sa.String(length=20), nullable=True),
    sa.Column('income', sa.String(length=100), nullable=True),
    sa.Column('income_proof', sa.String(length=100), nullable=True),
    sa.Column('org_legal_address', sa.Text(), nullable=True),
    sa.Column('org_fact_address', sa.Text(), nullable=True),
    sa.Column('org_activity', sa.String(length=100), nullable=True),
    sa.Column('assets', sa.String(length=255), nullable=True),
    sa.Column('extra_income', sa.String(length=255), nullable=True),
    sa.Column('contact_person', sa.Text(), nullable=True),
    sa.Column('active_credit', sa.Integer(), nullable=False),
    sa.Column('report_files', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("email ~ '^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$'", name='ck_clients_email_basic'),
    sa.CheckConstraint("phone_number ~ '^\\+?[1-9]\\d{7,14}$'", name='ck_clients_phone_e164'),
    sa.CheckConstraint('(taken_at_broker IS NULL) OR (broker_id IS NOT NULL)', name='ck_clients_broker_ts_consistency'),
    sa.CheckConstraint('(taken_at_worker IS NULL) OR (worker_id IS NOT NULL)', name='ck_clients_worker_ts_consistency'),
    sa.CheckConstraint('active_credit >= 0', name='ck_clients_active_credit_nonneg'),
    sa.CheckConstraint('char_length(btrim(full_name)) > 0', name='ck_clients_full_name_not_blank'),
    sa.ForeignKeyConstraint(['broker_id'], ['brokers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_clients_broker_id'), 'clients', ['broker_id'], unique=False)
    op.create_index(op.f('ix_clients_worker_id'), 'clients', ['worker_id'], unique=False)
    op.create_table('credits',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('broker_id', sa.UUID(), nullable=True),
    sa.Column('worker_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('approved_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('monthly_payment', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('bank_name', sa.String(length=120), nullable=True),
    sa.Column('first_payment_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'APPROVED', 'REJECTED', 'TREATMENT', 'COMPLETED', name='credit_status'), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['broker_id'], ['brokers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credits_is_deleted'), 'credits', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_credits_issued_at'), 'credits', ['issued_at'], unique=False)
    op.create_index(op.f('ix_credits_status'), 'credits', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_credits_status'), table_name='credits')
    op.drop_index(op.f('ix_credits_issued_at'), table_name='credits')
    op.drop_index(op.f('ix_credits_is_deleted'), table_name='credits')
    op.drop_table('credits')
    op.drop_index(op.f('ix_clients_worker_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_broker_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_table('workers')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('brokers')
    op.drop_table('admins')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_table('users')
    op.drop_table('registration_invites')
    op.drop_index(op.f('ix_promotions_is_deleted'), table_name='promotions')
    op.drop_table('promotions')
    # ### end Alembic commands ###
