import uuid
from pydantic import Field
from backend.app.schemas import SchemaBase

class UUIDSchema(SchemaBase):
    """
    Shared schema for models using UUID as a primary key.
    Typically used for output, as UUID is auto-generated by the database.
    """

    id: uuid.UUID = Field(..., description="Universally unique identifier (UUID v4)")
