import uuid
from pydantic import Field

class UUIDSchema:
    """
    Shared schema for models using UUID as a primary key.
    Typically used for output, as UUID is auto-generated by the database.
    """

    id: uuid.UUID = Field(..., description="Universally unique identifier (UUID v4)")
