"""Add RefreshToken model for JWT token management

Revision ID: 7cd3064336a8
Revises: 83d857ce6ead
Create Date: 2025-06-13 16:27:34.432547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cd3064336a8'
down_revision: Union[str, None] = '83d857ce6ead'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('token_hash', sa.String(length=64), nullable=False))
    op.add_column('refresh_tokens', sa.Column('created_from_ip', sa.String(length=45), nullable=True))
    op.drop_constraint(op.f('refresh_tokens_token_key'), 'refresh_tokens', type_='unique')
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_unique_constraint('uix_user_token', 'refresh_tokens', ['user_id', 'token_hash'])
    op.create_unique_constraint(None, 'refresh_tokens', ['token_hash'])
    op.drop_column('refresh_tokens', 'ip')
    op.drop_column('refresh_tokens', 'token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('token', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('refresh_tokens', sa.Column('ip', sa.VARCHAR(length=45), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'refresh_tokens', type_='unique')
    op.drop_constraint('uix_user_token', 'refresh_tokens', type_='unique')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.create_unique_constraint(op.f('refresh_tokens_token_key'), 'refresh_tokens', ['token'], postgresql_nulls_not_distinct=False)
    op.drop_column('refresh_tokens', 'created_from_ip')
    op.drop_column('refresh_tokens', 'token_hash')
    # ### end Alembic commands ###
