"""rename password to password_hash

Revision ID: dcb9e89a1c71
Revises: 9b4aeaed230a
Create Date: 2025-06-17 19:58:35.614711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcb9e89a1c71'
down_revision: Union[str, None] = '9b4aeaed230a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.drop_column('admins', 'password')
    op.add_column('brokers', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.drop_column('brokers', 'password')
    op.add_column('workers', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.drop_column('workers', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('workers', 'password_hash')
    op.add_column('brokers', sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('brokers', 'password_hash')
    op.add_column('admins', sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('admins', 'password_hash')
    # ### end Alembic commands ###
